common/models/Blog.php
<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\helpers\Html;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Inflector;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "blog".
 *
 * @property string $blog_id
 * @property string $restaurant_id
 * @property string $blog_title
 * @property string $blog_text
 * @property string $blog_image
 * @property integer $blog_status
 * @property string $created_at
 *
 * @property Restaurants $restaurant
 */
class Blog extends \yii\db\ActiveRecord
{
    const POST_STATUS_INACTIVE = 0;
    const POST_STATUS_ACTIVE   = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['restaurant_id', 'blog_title', 'blog_text'], 'required'],
            [['blog_title', 'blog_text'], 'trim'],
            [['restaurant_id', 'blog_status'], 'integer'],
            [['blog_status'], 'default', 'value' => self::POST_STATUS_INACTIVE],
            [['blog_text'],  'string'],
            [['blog_title'], 'string', 'max' => 255],
            [['blog_title'], 'filter', 'filter' => 'strip_tags'],
            [['blog_image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg'],
            [['restaurant_id'], 'exist', 'skipOnError' => true, 'targetClass' => Restaurants::className(), 'targetAttribute' => ['restaurant_id' => 'restaurant_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'blog_id'       => 'Blog ID',
            'restaurant_id' => 'Автор',
            'blog_title'    => 'Названия статьи',
            'blog_text'     => 'Текстовый редактор',
            'blog_image'    => 'Изображение',
            'blog_status'   => 'Статус',
            'created_at'    => 'Создано',
        ];
    }

    /**
     * @return array
     */
    public function behaviors() {
        $behaviors         = parent::behaviors();
        $behaviors['slug'] = [
            'class'         => SluggableBehavior::className(),
            'slugAttribute' => 'uri',
            'ensureUnique'  => true,
            'value'         => function ($event) {
                if (!empty($event->sender->uri)) {
                    return $event->sender->uri;
                }

                return Inflector::slug('b-' . $event->sender->blog_title);
            },
        ];
        $behaviors['timestamp'] = [
            'class'      => TimestampBehavior::className(),
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'created_at',
            ],
            'value' => function() { return date('U');}
        ];

        return $behaviors;
    }

    /**
     * Return post
     * @param $id
     * @return array|ActiveRecord[]
     */
    public static function findModel($id)
    {
        return static::find()->where([
            'blog_id' => $id,
        ])->one();
    }

    public static function getModels()
    {
        return static::find()->where(['blog_status' => self::POST_STATUS_ACTIVE]);
    }

    /**
     * @return string
     */
    public function getAvatar() {
        if($this->blog_image) {
            $path = '/upload/blog/' . $this->blog_image;
        } else {
            $path = '/img/dish1.jpg';
        }

        return $path;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRestaurant()
    {
        return $this->hasOne(Restaurants::className(), ['restaurant_id' => 'restaurant_id']);
    }

    public function getStatus($status = null) {
        $data = [
            0 => 'В ожидании',
            1 => 'Одобрено'
        ];

        return $status !== null ? $data[$status] : $data;
    }

    /**
     * Is restaurant have a not approved posts
     * @param int $restId
     * @return string
     */
    public static function isApproved($restId) {
        if($count = count(Blog::find()->where([
            'restaurant_id' => $restId,
            'blog_status'   => self::POST_STATUS_INACTIVE
        ])->all())) {
            return Html::a('Есть: ' . $count, ['blog/index', 'restId' => $restId], ['class' => 'btn-warning']);
        } else {
            return Html::tag('p', 'Нет', ['class' => 'btn-success']);
        }
    }

    public function getImg($module = null)
    {
        if($this->blog_image) {
            if($module == 'admin') {
                return Yii::$app->params['uploadUrl'] . '/blog/' . $this->blog_image;
            }

            return '/upload/blog/' . $this->blog_image;
        } else {
            return '/img/dish1.jpg';
        }
    }

    /**
     * Return posts
     * @param $uri
     * @return array|null|\yii\db\ActiveRecord
     */
    public static function findModelByUri($uri)
    {
        return static::find()->where(['uri' => $uri])->with('comments.user.userProfile')->one();
    }

    public static function getLastPosts($limit = 3)
    {
        return static::find()->limit($limit)
                             ->orderBy('created_at DESC')
                             ->where(['blog_status' => self::POST_STATUS_ACTIVE])
                             ->all();
    }

    public static function getClasses() {
        return [
            '',
            'grid-item--width2',
            'grid-item--width3'
        ];
    }

    public function getComments()
    {
        return $this->hasMany(Comments::className(), ['entity_id' => 'blog_id'])
            ->where([
                'comment_entity' => Comments::ENTITY_BLOG,
                'comment_status' => Comments::COMMENT_ACTIVE
            ]);
    }

    public static function getPostsForSearch($search) {
        return static::find()->filterWhere(['like', 'blog_title', $search])->all();
    }
}

backend/controllers/BlogController.php
<?php

namespace backend\controllers;

use common\models\Restaurants;
use Yii;
use common\models\Blog;
use backend\models\BlogSearch as BlogSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use common\lybrary\upload\Upload;

/**
 * BlogController implements the CRUD actions for Blog model.
 */
class BlogController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Blog models.
     * @param int $restId
     * @return mixed
     */
    public function actionIndex($restId)
    {
        $searchModel  = new BlogSearch();
        $rest         = Restaurants::findOne($restId);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
            'rest'         => $rest
        ]);
    }

    /**
     * Displays a single Blog model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Blog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $modelBlog = new Blog();
        $request   = \Yii::$app->request;

        if ($request->isPost && $modelBlog->load($request->post())) {
            $file   = UploadedFile::getInstance($modelBlog, 'blog_image');
            $upload = new Upload();

            if($file) {
                $upload->setFile($file)
                    ->setFileExtensions(['jpg', 'png', 'jpeg'])
                    ->setMaxSize(6)
                    ->setFileRename(true)
                    ->addThumbnails([['path' => 'upload/blog']])
                    ->setQuality(60)
                    ->setMinCompressSize(0)
                    ->upload();

                if (!$upload->isErrorExists()) {
                    $modelBlog->blog_image = $upload->getFileName();
                }
            }
            $modelBlog->restaurant_id = $id;
            $modelBlog->save();

            return $this->redirect(['view', 'id' => $modelBlog->blog_id]);
        } else {
            return $this->render('create', [
                'model' => $modelBlog,
            ]);
        }
    }

    /**
     * Updates an existing Blog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $blog    = $this->findModel($id);
        $request = \Yii::$app->request;

        if ($request->isPost && $blog->load($request->post())) {
            $file   = UploadedFile::getInstance($blog, 'blog_image');
            $upload = new Upload();

            if($file) {
                $upload->setFile($file)
                       ->setFileExtensions(['jpg', 'png', 'jpeg'])
                       ->setMaxSize(6)
                       ->setFileRename(true)
                       ->addThumbnails([['path' => 'upload/blog']])
                       ->setQuality(60)
                       ->setMinCompressSize(0)
                       ->upload();

                if (!$upload->isErrorExists()) {
                    $blog->blog_image = $upload->getFileName();

                    if($oldImage = $blog->oldAttributes['blog_image']) {
                        Upload::clearThumbnails('blog', $oldImage);
                    }
                }
            } else {
                $blog->blog_image = $blog->oldAttributes['blog_image'];
            }

            $blog->save();

            return $this->redirect(['view', 'id' => $blog->blog_id]);
        } else {
            return $this->render('update', [
                'model' => $blog,
            ]);
        }
    }

    /**
     * Deletes an existing Blog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Blog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Blog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Blog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Approved post
     * @param int $id
     * @return mixed
     */
    public function actionApprovedPost($id)
    {
        $blog              = $this->findModel($id);
        $blog->blog_status = Blog::POST_STATUS_ACTIVE;
        $blog->save();

        return $this->redirect(['index', 'restId' => $blog->restaurant_id]);
    }
}

frontend/controllers/BlogController.php
<?php

namespace frontend\controllers;

use common\lybrary\upload\Upload;
use common\models\Blog;
use common\models\Comments;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * Class BlogController
 * @author Maksim Nikitenko <lycifer3.mn@gmail.com>
 * @package frontend\controllers
 */
class BlogController extends BaseController {

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['post-save', 'delete'],
                'rules' => [
                    [
                        'actions' => ['post-save', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Blog::getModels(),
            'pagination' => [
                'pageSize' => \Yii::$app->params['perPage'],
            ],
        ]);

        return $this->render('index', [
            'provider' => $dataProvider
        ]);
    }

    public function actionView($uri)
    {
        $blog          = Blog::findModelByUri($uri);
        $lastPosts     = Blog::getLastPosts();
        $commentsModel = new Comments();

        return $this->render('view', [
            'blog'          => $blog,
            'lastPosts'     => $lastPosts,
            'user'          => $this->user,
            'commentsModel' => $commentsModel
        ]);
    }

    /**
     * Save comment
     * @param $uri
     * @return Response
     */
    public function actionSaveComment($uri) {
        $request      = \Yii::$app->request;
        $commentModel = new Comments();

        if($request->isPost && $commentModel->load($request->post())) {
            $commentModel->user_id        = $this->user->id;
            $commentModel->comment_entity = Comments::ENTITY_BLOG;

            if($commentModel->save()) {
                \Yii::$app->session->setFlash('comment', 'Коментарий добавлен, появится на сайте после модерации');

                return $this->redirect(Url::to(['/blog/view', 'uri' => $uri, '#' => 'commentsForm']));
            } else {
                \Yii::$app->session->setFlash('comment', 'Что то пошло не так попробуйте еще раз');

                return $this->redirect(Url::to(['/blog/view', 'uri' => $uri, '#' => 'commentsForm']));
            }
        }
    }

    /**
     * Create/update blog post
     * @return string
     */
    public function actionPostSave() {
        $request = \Yii::$app->request;
        $params  = $request->get();
        $model   = new Blog();

        if($params['id']) {
            $model = Blog::findModel($params['id']);
        }

        if($request->isAjax) {
            return $this->renderAjax('_blog-form', [
                'model'  => $model,
                'restId' => $params['restId']
            ]);
        }

        if($request->isPost && $model->load($request->post())) {
            $file   = UploadedFile::getInstance($model, 'blog_image');
            $upload = new Upload();

            if($file) {
                if($model->blog_image) {
                    Upload::clearThumbnails('blog', $model->blog_image);
                }

                $upload->setFile($file)
                       ->setFileExtensions(['jpg', 'png', 'jpeg'])
                       ->setMaxSize(6)
                       ->setFileRename(true)
                       ->setFileCompress(true)
                       ->addThumbnails([['path' => '/upload/blog']])
                       ->setQuality(60)
                       ->setMinCompressSize(0)
                       ->upload();

                if (!$upload->isErrorExists()) {
                    $model->blog_image = $upload->getFileName();
                }
            }

            if($model->save()) {
                return $this->redirect(Url::to(['/restaurant/profile', 'post' => true]));
            }
        }
    }

    /**
     * Delete blog post
     * @param $id
     * @return Response
     */
    public function actionDelete($id) {
        if($id) {
            $model = Blog::findModel($id);

            if($model->delete()) {
                return $this->redirect(Url::to(['/restaurant/profile', 'post' => true]));
            }
        }
    }
}

frontend/views/blog/_blog-form.php
<?php
/** @var Blog $model */

use common\models\Blog;
use vova07\imperavi\Widget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

?>

<div class="row">
    <?php $form = ActiveForm::begin([
        'id'     => 'blogForm',
        'action' => Url::to(['/blog/post-save', 'id' => $model->blog_id ?: null]),
        'method' => 'post'
    ]); ?>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-upload restaurant-profile-img">
                        <div class="upload-thumb upload-thumb-rest">
                            <img id="js-blog-preview" src="<?= $model->getAvatar(); ?>" alt="">
                        </div>
                        <div class="upload-btn animate">
                            Загрузить главное фото
                            <?= $form->field($model, 'blog_image', [
                                'options' => ['tag' => false]
                            ])->fileInput(['id' => 'js-blog-img'])->label(false); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="rest-form-sett">
                <?= $form->field($model, 'restaurant_id')->hiddenInput(['value' => $restId])->label(false); ?>

                <?= $form->field($model, 'blog_title')->textarea([
                    'class' => 'form-control',
                    'rows'  => '2'
                ]); ?>

                <?= $form->field($model, 'blog_text')->widget(Widget::className(), [
                    'settings' => [
                        'lang' => 'ru',
                        'minHeight' => 200,
                    ],
//                'class' => 'form-control',
//                'rows'  => '4'
                ]); ?>
                <button type="submit" class="animate btn btn-light btn-lg submit-btn">
                    <?php if($model->isNewRecord): ?>
                        Опубликовать
                    <?php else: ?>
                        Сохранить
                    <?php endif; ?>
                </button>
                <?php if($model->blog_status == Blog::POST_STATUS_ACTIVE): ?>
                    <a href="#" class="animate btn btn-light btn-lg">Посмотреть</a>
                <?php endif; ?>
            </div>

        </div>

    <?php ActiveForm::end(); ?>
</div>

frontend/views/blog/index.php
<?php
/** @var Blog $blog */

use common\models\Blog;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->title = 'Блог';
?>


<!-- Page header section start -->
<section class="page-title" style="background-image: url(img/news-bg.jpg)">
    <div class="container">
        <h1 class="lora text-center">Блог</h1>
    </div>
</section>
<!-- Page header section end -->

<!-- News grid section start -->
<section class="news">
    <div class="container">
        <div class="grid news-list masonry-news clearfix">
            <?php foreach ($provider->getModels() as $blog): ?>
                <div class="grid-item grid-item-abs">
                    <a href="<?= Url::to(['view', 'uri' => $blog->uri]); ?>" class="new-item">
                        <div class="new-item__thumb">
                            <img src="<?= $blog->getImg(); ?>" alt="">
                        </div>
                        <div class="new-item__caption">
                            <h3 class="new-item__title lora"><?= $blog->blog_title; ?></h3>
                            <div class="new-item__date"><?= Yii::$app->formatter->asDate($blog->created_at, 'php:d.m.Y'); ?></div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
            <div class="grid-sizer"></div>
        </div>
        <nav class="post-navigation">
            <?= LinkPager::widget([
                'pagination' => $provider->pagination,
            ]);?>
        </nav>
    </div>
</section>
<!-- News grid section end -->

frontend/views/blog/view.php
<?php
/** @var Blog $blog */

use common\models\Blog;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $blog->blog_title;
$userProfile = $user->userProfile;
?>


<!-- Page header section start -->
<section class="page-title" style="background-image: url(/img/new-bg.jpg)">
    <div class="container">
        <a href="<?= Url::to(['index']); ?>" class="page-title__back btn-stroke btn btn-sm animate pull-left">Назад</a>
        <h1 class="lora text-center">Блог</h1>
    </div>
</section>
<!-- Page header section end -->

<!-- New content section start -->
<section class="new-single">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="new-single__header">
                    <h2 class="new-single__title lora"><?= $blog->blog_title; ?></h2>
                    <div class="new-single__date"><?= Yii::$app->formatter->asDate($blog->created_at, 'php:d.m.Y'); ?></div>
                    <div class="new-single__image">
                        <img src="<?= $blog->getImg(); ?>" alt="">
                    </div>
                </div>
                <div class="new-single__content">
                    <?= $blog->blog_text; ?>
                </div>
            </div>
            <div class="rest-content__reviews">
                <h3 class="lora">Коментарии <span class="badge"><?= count($blog->comments); ?></span></h3>
                <div class="row">
                    <?php if(!empty($blog->comments)): ?>
                        <?php foreach ($blog->comments as $comment): ?>
                            <?php
                                $author        = $comment->user;
                                $authorProfile = $author->userProfile;
                            ?>
                            <div class="col-lg-6">
                                <div class="review-item">
                                    <div class="review-item__header">
                                        <div class="review-item__title">
                                            <img src="<?= $authorProfile ? $authorProfile->getAvatar() : '/img/avatar-default.jpg' ?>" alt="" class="review-item__avatar">
                                            <div class="review-item__name"><?= $authorProfile ? $authorProfile->getFullName() : $author->email ?></div>
                                        </div>
                                        <div class="review-item__text">
                                            <?= $comment->comment_text; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <?php if(Yii::$app->user->isGuest): ?>
                    <div class="review-item no-login text">Чтобы добавить коментарий,
                        <a href="#" data-toggle="modal" data-target="#login-modal">войдите</a> или
                        <a href="#" data-toggle="modal" data-target="#signin-modal">зарегестрируйтесь</a>.
                    </div>
                <?php else: ?>
                    <?php $form = \yii\bootstrap\ActiveForm::begin([
                        'id'                     => 'commentsForm',
                        'action'                 => Url::to(['/blog/save-comment', 'uri' => $blog->uri]),
                        'method'                 => 'post',
                        'enableClientValidation' => true,
                        'options' => [
                            'validateOnSubmit' => true,
                        ]
                    ]); ?>
                    <div class="review-item add-review">
                        <div class="review-item__header">
                            <div class="review-item__title">
                                <img src="<?= $userProfile ? $userProfile->getAvatar() : '/img/avatar-default.jpg' ?>" alt="" class="review-item__avatar">
                                <div class="review-item__name"><?= $userProfile ? $userProfile->getFullName() : $user->email ?></div>
                            </div>
                            <div class="review-item__text">
                                <?= $form->field($commentsModel, 'comment_text')->textarea([
                                    'class' => 'string-textarea',
                                    'placeholder' => 'Напишите коментарий...'
                                ])->label(false); ?>
                            </div>
                            <?= $form->field($commentsModel, 'entity_id')->hiddenInput([
                                'value' => $blog->blog_id
                            ])->label(false); ?>
                        </div>
                    </div>
                    <?= Html::button('Добавить коментарий', [
                    'class' => 'animate btn btn-light btn-lg btn-block',
                    'type'  => 'submit'
                ])?>
                    <?php \yii\bootstrap\ActiveForm::end(); ?><br>
                    <?php if($message = Yii::$app->session->getFlash('comment')): ?>
                        <div class="alert alert-success" role="alert"><?= $message ?></div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
<!-- New content section end -->

<!-- Other news section start -->
<section class="other-news">
    <div class="container">
        <h2 class="lora text-center">Похожие записи блога</h2>
        <div class="news-list clearfix">
            <?php foreach ($lastPosts as $item): ?>
                <div class="grid-item grid-item-static grid-item--width3">
                    <a href="<?= Url::to(['view', 'uri' => $item->uri]); ?>" class="new-item">
                        <div class="new-item__thumb">
                            <img src="<?= $item->getImg(); ?>" alt="">
                        </div>
                        <div class="new-item__caption">
                            <h3 class="new-item__title lora"><?= $item->blog_title; ?></h3>
                            <div class="new-item__date"><?= Yii::$app->formatter->asDate($item->created_at, 'php:d.m.Y'); ?></div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>
<!-- Other news section start -->